<!Doctype html>
<html lang = en>

<head>
    <?php include '../MAIN_INCLUDE31986/HEADPARTHTML31986.PHP'?>
</head>
<body>
    <header>
        <?php include '../MAIN_INCLUDE31986/HEADER31986.PHP'?>
    </header>
    <article>
        <?php include '../MAIN_INCLUDE31986/ARTICLE31986.PHP'?>
        <img src="..\IMG31986\fotografia31986.jpg" alt="image"><br>
        <?php include '../DB_INCLUDE31986/DB31986.PHP'?>
        <?php include '../DB_WORK31986/ADD31986/CZYADD_KURSY31986.PHP'?>
        <?php include '../DB_WORK31986/ADD31986/DOADD_KURSY31986.PHP'?>
        <?php include '../DB_WORK31986/SELECT31986/SELECT_KURSY31986.PHP'?>
        <?php include '../MAIN_INCLUDE31986/NAV31986.PHP'?>
    </article>
    
    <footer>
        <?php include '../MAIN_INCLUDE31986/FOOTER31986.PHP'?>
    </footer>
</body>
</html>