<?php 
$select = '<table>
<tr>
    <td><a href= "SEE_FOTOGRAF_MAJSTER31986.PHP">Zobacz fotografów</td>
    <td><a href= "SEE_FOTOGRAF_MAJSTER_UMIEJETNOSCI31986.PHP">Zobacz umiejętoności fotografów</td>
    <td><a href= "SEE_INFO_ZAJECIA31986.PHP">Zobacz informacje o zajęciach</td>
    <td><a href= "SEE_KURSY31986.PHP">Zobacz kursy</td>
    <td><a href= "SEE_RODZAJE31986.PHP">Zobacz rodzaje kursów</td>
</tr>
<tr>
    <td><a href= "ADD_FOTOGRAF_MAJSTER31986.PHP">Dodaj fotografów</td>
    <td><a href= "ADD_FOTOGRAF_MAJSTER_UMIEJETNOSCI31986.PHP">Dodaj umiejętoności fotografów</td>
    <td><a href= "ADD_INFO_ZAJECIA31986.PHP">Dodaj informacje o zajęciach</td>
    <td><a href= "ADD_KURSY31986.PHP">Dodaj kursy</td>
    <td><a href= "ADD_RODZAJE31986.PHP">Dodaj rodzaje kursów</td>
</tr>
</table>';

echo $select?>